services:
  github-runner:
    build:
      context: .
      args:
        RUNNER_ARCH: x64
        DOCKER_GID: ${DOCKER_GID}
        RUNNER_GID: ${RUNNER_GID}

    env_file:
      - .env

    environment:
      LABELS: linux,x64,docker
      GIT_REPOSITORY: ${GIT_REPOSITORY}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./workspace:/github/workspace  # Маунт для файлов репозитория

    restart: unless-stopped
