services:
  registry:
    image: registry:2
    container_name: registry
    hostname: registry
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      TZ: "Europe/Moscow"
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/public.pem
      REGISTRY_HTTP_TLS_KEY: /certs/private.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_STORAGE_DELETE_ENABLED: true
    volumes:
      - ./registry:/var/lib/registry
      - ./ssl:/certs
      - ./auth:/auth
